// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCx8qVtfuxkx9_hUU2IajQR1RzpsUhgtSk',
//     appId: '1:145091405497:web:01635d1251c63541ab1d68',
//     messagingSenderId: '145091405497',
//     projectId: 'zebull-flutter-9380e',
//     authDomain: 'zebull-flutter-9380e.firebaseapp.com',
//     storageBucket: 'zebull-flutter-9380e.appspot.com',
//     measurementId: 'G-68G37B78XE',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAsQh_k2F4qx8YeSJ9zDGEfpXBZxdp6bQ0',
//     appId: '1:145091405497:android:4cdb8ad6b3a19164ab1d68',
//     messagingSenderId: '145091405497',
//     projectId: 'zebull-flutter-9380e',
//     storageBucket: 'zebull-flutter-9380e.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCNtFrrD8cAxTMmo_btPrEaIHT5HFCBNUY',
//     appId: '1:145091405497:ios:9127d0340e100e01ab1d68',
//     messagingSenderId: '145091405497',
//     projectId: 'zebull-flutter-9380e',
//     storageBucket: 'zebull-flutter-9380e.appspot.com',
//     iosBundleId: 'com.mynt.tradingappzebu',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCNtFrrD8cAxTMmo_btPrEaIHT5HFCBNUY',
//     appId: '1:145091405497:ios:ef901106068bd2c5ab1d68',
//     messagingSenderId: '145091405497',
//     projectId: 'zebull-flutter-9380e',
//     storageBucket: 'zebull-flutter-9380e.appspot.com',
//     iosBundleId: 'com.mynt.tradingappzebu.RunnerTests',
//   );
// }
